include: package:lints/recommended.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true
    prefer_const_constructors: true
    always_put_required_named_parameters_first: true